use std::path::Path;

use color_eyre::{Result, eyre::eyre};

use crate::config::project_config::{BuildConfig, ModuleConfig};

/// Module option entry for generating CMake CACHE variables.
struct CmakeOption {
    variable: &'static str,
    description: &'static str,
    enabled: bool,
}

/// Write cmake-local/options.cmake with CACHE variable overrides.
pub fn write_options_cmake(
    modules: &ModuleConfig,
    build: &BuildConfig,
    output_dir: &Path,
) -> Result<()> {
    let options = vec![
        CmakeOption {
            variable: "ENABLE_MOONBASE",
            description: "Enable Moonbase licensing",
            enabled: modules.moonbase,
        },
        CmakeOption {
            variable: "ENABLE_MELATONIN",
            description: "Enable Melatonin Inspector",
            enabled: modules.melatonin,
        },
        CmakeOption {
            variable: "ENABLE_CLAP",
            description: "Enable CLAP plugin format",
            enabled: modules.clap,
        },
        CmakeOption {
            variable: "ENABLE_DIREKTDSP_GUI",
            description: "Enable DirektDSP GUI framework",
            enabled: modules.direktdsp_gui,
        },
        CmakeOption {
            variable: "ENABLE_CYCFI_Q",
            description: "Enable cycfi::Q DSP library",
            enabled: modules.cycfi_q,
        },
        CmakeOption {
            variable: "ENABLE_COMMON_LAYER",
            description: "Enable common implementation layer",
            enabled: modules.common_layer,
        },
    ];

    let mut lines = vec![
        "# options.cmake - Generated by DirektDSP Configurator".to_string(),
        "# Sets default values for module toggle options.".to_string(),
        "# These are CACHE variables, so they can be overridden with -D flags.".to_string(),
        String::new(),
    ];

    for opt in &options {
        let value = if opt.enabled { "ON" } else { "OFF" };
        lines.push(format!(
            "set({} {} CACHE BOOL \"{}\")",
            opt.variable, value, opt.description
        ));
    }

    // Build options
    lines.push(String::new());
    lines.push("# Build options".to_string());
    lines.push(format!(
        "set(CMAKE_CXX_STANDARD {} CACHE STRING \"C++ standard\")",
        build.cpp_standard
    ));
    lines.push(format!(
        "set(COPY_PLUGIN_AFTER_BUILD {} CACHE BOOL \"Copy plugin after build\")",
        if build.copy_after_build { "ON" } else { "OFF" }
    ));
    if build.ipp {
        lines.push("set(USE_IPP ON CACHE BOOL \"Use Intel IPP\")".to_string());
    }

    lines.push(String::new()); // trailing newline

    let cmake_local_dir = output_dir.join("cmake-local");
    std::fs::create_dir_all(&cmake_local_dir)
        .map_err(|e| eyre!("Failed to create cmake-local directory: {e}"))?;

    let path = cmake_local_dir.join("options.cmake");
    std::fs::write(&path, lines.join("\n"))
        .map_err(|e| eyre!("Failed to write options.cmake: {e}"))?;

    Ok(())
}
